philippgille/gokv

.travis.yml, README.md, RELEASES.md, mongodb/docs.go, mongodb/mongodb.go, mongodb/mongodb_test.go
=> Add gokv.Store implementation for MongoDB

file/file.go, file/file_test.go
- Also make it explicitly settable instead of setting it according to the Codec,
because the Codec can be a user-supplied one.
Closes #56.
=> Make filename extension optional

gomap/gomap.go, test/test.go
delete is not thread safe and must be synchronized
=> Fix gomap datarace

README.md, encoding/codec.go, encoding/go.mod, encoding/go.sum, encoding/proto.go
According to proto documentation,
protojson produces a different output than the standard "encoding/json" package, 
which does not operate correctly on protocol buffer messages.
Fixes #128
=> Adding encoding support for Protocol Buffers

.github/workflows/test.yml
=> ci: add more go versions for compatibility testing

.github/workflows/test.yml
Double builds were triggered when a maintainer pushed a new commit to an open PR, as it matched the push and the pull_request trigger. This didn't happen when contributors pushed to PRs, as that only triggered the pull_request one.
=> Fix CI double builds

.github/workflows/test.yml, magefiles/magefile.go, magefiles/test.go
=> ci: add windows to matrix tests

magefiles/test.go
The deferred function set `err` when it wasn't set yet, but without a named return that doesn't do anything. See https://go.dev/play/p/tuj8tJfOpQL
=> Improve error handling in magefile

.github/workflows/test.yml, magefiles/test.go
Maybe we should provide a tool installer in the magefile? Like `mage setup` or `mage install` and it installs all required CLI tools in the versions we use?
Or maybe better to change the magefile to check if tparse is installed, and only use it when it is?
=> Use tparse for test output

magefiles/test.go
for this TODO: https://github.com/philippgille/gokv/blob/bfdf6b8737b91a56a583bd4eafdad2b6abebf088/magefiles/test.go#L125
this is how it looks like now with new addition, note `healthy` :
```
$ docker ps
CONTAINER ID   IMAGE                                                                  COMMAND                  CREATED         STATUS                   PORTS                                NAMES
c0eee103bf34   cockroachdb/cockroach                                                  "/cockroach/cockroac…"   6 minutes ago   Up 6 minutes (healthy)   8080/tcp, 0.0.0.0:26257->26257/tcp   cockroachdb
```
=> feat: add healthcheck to tests

magefiles/test.go
After @glimchb added many Docker health checks in https://github.com/philippgille/gokv/pull/142, we can now make use of it for decreasing the wait time for a container to be running.
=> Use Docker health check to decrease wait for container

.github/workflows/test.yml
Update `actions/checkout` from v3 to v4, and `actions/setup-go` from v3 to v4.
Makes use of suppressing progress during Git checkout, and configures Go dependency caching.
=> Update and improve usage of GitHub Actions dependencies

magefiles/test.go
Due to default 30s interval, many containers waited 30s despite being ready after a few seconds
=> Reduce test container wait time

magefiles/test.go
Following the [initial PR](https://github.com/philippgille/gokv/pull/142) that added health checks, an improvement in https://github.com/philippgille/gokv/pull/162 and the *use* of the health checks in https://github.com/philippgille/gokv/pull/154, we should use the health checks in as many test containers as possible, to benefit from the mechanism and reduce build time in CI.
This PR adds health checks for Consul and Memcached.
As their images don't have the necessary tooling installed by default, and we don't want to execute the main server process as `root`, we instead run a separate `docker exec` command to install the required tooling, *while* the health checks are already running (but running into errors like "curl not found").
=> Add Docker health checks to Consul and Memcached

etcd/etcd_test.go
As the code comment says, there are issues with the concurrency test for etcd in CI, but they are not reproducible locally, and also don't *always* happen in CI.
Previous fix attempts haven't worked:
- https://github.com/philippgille/gokv/pull/169
- https://github.com/philippgille/gokv/pull/170
We skip the test in CI as a temporary workaround, and before a release we can and should run all tests locally to include this one.
I also searched a bit on the web, the [etcd GitHub Discussions](https://github.com/etcd-io/etcd/discussions) and their [Google Group](https://groups.google.com/g/etcd-dev).
In the future we could post a question in one of their communities.
=> Skip etcd concurrency test in CI

cockroachdb/cockroachdb_test.go, consul/consul_test.go, datastore/datastore_test.go, dynamodb/dynamodb_test.go, etcd/etcd_test.go, hazelcast/hazelcast_test.go, ignite/ignite_test.go, memcached/memcached_test.go, mongodb/mongodb_test.go, mysql/mysql_test.go, postgresql/postgresql_test.go, redis/redis_test.go, s3/s3_test.go, zookeeper/zookeeper_test.go
In the past, probably before we had the `mage test all` that automatically spins up Docker containers for the different store implementation tests, it was useful to do connection tests and skip tests when no connection could be established, to not fail an entire test run, but instead allow to check in the output log for any _unexpected_ skips.
The Docker container start has been very reliable though, while OTOH I've been less often checking for skipped tests, and it's also cumbersome to check with the long test output (and not using `tparse` yet).
=> This PR removes the connection check and test skipping from almost all store implementation tests.
The exceptions:
- tablestorage and tablestore: Their test containers don't yet work correctly. So far they need to be tested locally, with …
=> Remove test skipping on connection error

test/test.go
A [past change](https://github.com/philippgille/gokv/commit/6757d687d02d6e17053e690a382ebcde3e17eb1a) added the delete but forgot the required write
=> Fix concurrency tests

sql/go.mod, sql/go.sum
We previously only updated the gokv/test dependency, but not the gokv/encoding one.
For the process see https://github.com/philippgille/gokv/tree/v0.7.0/docs/releasing.md
=> Fix missing gokv/sql update

.github/workflows/test.yml, .golangci.yml
- Updated Go versions to minimum 1.21 (for compatibility with new go directive version syntax, e.g. required [here](https://github.com/philippgille/gokv/pull/201)), and including all versions released since then
- Updated all GitHub Actions versions to their latest available version
- The latest Codecov Action version requires a token (if not disabling that requirement in the Codecov settings), so I've added it to the repo secrets and referencing it in the Action configuration
=> Update Go and GitHub Actions for CI

.github/workflows/ci.yml
We're reducing the size of the build matrix in CI, to speed up the GitHub Actions. We're now testing the latest 2 Go versions, same as what the Go team officially supports: https://go.dev/doc/devel/release#policy
We try to keep `gokv` compatible with older versions as well, we're just not testing it in CI anymore. If you run into issues with an older version please let us know, we can look into it and maybe adapt accordingly.
=> Remove Go 1.21 and 1.22 from CI build matrix
