philippgille/gokv

README.md, RELEASES.md, bolt/bolt.go, bolt/bolt_test.go, docs.go, redis/redis.go, redis/redis_test.go, store.go, syncmap/map.go, syncmap/map_test.go, test/test.go, util/util.go
=> Separate package per store implementation

README.md, RELEASES.md, gomap/map.go, gomap/map_test.go
=> Add go map as store implementation

RELEASES.md, bolt/bolt.go
=> Fix errors occur when reading a value from the store implementation for bbolt / Bolt DB

README.md, RELEASES.md, bolt/bolt.go, gomap/map.go, redis/redis.go, store.go, syncmap/map.go, test/test.go
=> Add delete method

README.md, RELEASES.md, badgerdb/badgerdb.go, badgerdb/badgerdb_test.go, bolt/bolt.go
=> Add Store implementation for BadgerDB

.travis.yml, README.md, RELEASES.md, consul/consul.go, consul/consul_test.go
=> Add Store implementation for Consul

badgerdb/badgerdb_test.go, bolt/bolt_test.go, consul/consul_test.go, gomap/map_test.go, redis/redis_test.go, syncmap/map_test.go, test/test.go
=> Add test for more data types

.travis.yml, README.md, RELEASES.md, etcd/docs.go, etcd/etcd.go, etcd/etcd_test.go
=> Add gokv.Store implementation for etcd

.travis.yml, README.md, RELEASES.md, dynamodb/docs.go, dynamodb/dynamodb.go, dynamodb/dynamodb_test.go
=> Add gokv.Store implementation for Amazon DynamoDB

.travis.yml, README.md, RELEASES.md, mysql/docs.go, mysql/mysql.go, mysql/mysql_test.go
=> Add gokv.Store implementation for MySQL

.travis.yml, README.md, RELEASES.md, memcached/docs.go, memcached/memcached.go, memcached/memcached_test.go
=> Add gokv.Store implementation for Memcached

README.md, RELEASES.md, badgerdb/badgerdb.go, badgerdb/badgerdb_test.go, bbolt/bbolt.go, bbolt/bbolt_test.go, consul/consul.go, consul/consul_test.go, docs.go, dynamodb/dynamodb.go, dynamodb/dynamodb_test.go, etcd/etcd.go, etcd/etcd_test.go, examples/main.go, gomap/map.go, gomap/map_test.go, memcached/memcached.go, memcached/memcached_test.go, mongodb/mongodb.go, mongodb/mongodb_test.go, mysql/mysql.go, mysql/mysql_test.go, redis/redis.go, redis/redis_test.go, store.go, syncmap/map.go, syncmap/map_test.go
=> Add Close() method to interface and all implementations

.travis.yml, README.md, RELEASES.md, tablestorage/docs.go, tablestorage/tablestorage.go, tablestorage/tablestorage_test.go
=> Add gokv.Store implementation for Azure Table Storage

.travis.yml, README.md, RELEASES.md, freecache/docs.go, freecache/freecache.go, freecache/freecache_test.go
=> Add gokv.Store implementation for FreeCache

.gitignore, .travis.yml, README.md, RELEASES.md, leveldb/docs.go, leveldb/leveldb.go, leveldb/leveldb_test.go
=> Add gokv.Store implementation for LevelDB

.travis.yml, README.md, RELEASES.md, datastore/datastore.go, datastore/datastore_test.go, datastore/docs.go
=> Add gokv.Store implementation for Google Cloud Datastore

.travis.yml, README.md, RELEASES.md, file/docs.go, file/file.go, file/file_test.go
=> Add gokv.Store implementation for storing key-value pairs as files

.travis.yml, README.md, RELEASES.md, docs/choosing-implementation.md, s3/docs.go, s3/s3.go, s3/s3_test.go
=> Add gokv.Store implementation for Amazon S3

.travis.yml, README.md, RELEASES.md, docs/choosing-implementation.md, mysql/mysql.go, mysql/mysql_test.go, postgresql/docs.go, postgresql/postgresql.go, postgresql/postgresql_test.go, sql/sql.go
=> Add gokv.Store implementation for PostgreSQL

.travis.yml, README.md, RELEASES.md, cockroachdb/cockroachdb.go, cockroachdb/cockroachdb_test.go, cockroachdb/docs.go, docs/choosing-implementation.md, mysql/mysql.go, postgresql/postgresql.go, sql/sql.go
=> Add gokv.Store implementation for CockroachDB

.travis.yml, README.md, RELEASES.md, docs/choosing-implementation.md, zookeeper/docs.go, zookeeper/zookeeper.go, zookeeper/zookeeper_test.go
=> Add gokv.Store implementation for Apache ZooKeeper

.travis.yml, README.md, RELEASES.md, docs/choosing-implementation.md, hazelcast/docs.go, hazelcast/hazelcast.go, hazelcast/hazelcast_test.go
=> Add gokv.Store implementation for Hazelcast

.github/workflows/test.yml
=> ci: use GitHub Action for Mage

datastore/datastore.go
following https://github.com/philippgille/gokv/commit/9c5b7d72f129ab5b7df52ef80b7ae280ace2db80
=> feat(datastore): introduce timeout configuration

magefiles/test.go
Can otherwise clash with already running containers on the host
=> Prefix test container names with gokv

sql/go.mod, sql/go.sum, test/go.mod, test/go.sum
As per <https://github.com/philippgille/gokv/tree/v0.7.0/docs/releasing.md>
=> Update gokv/sql and gokv/test to latest gokv version

encoding/protobuf/protobuf.go
=> fix typo in godoc
